import {
  AgentSessionRecord,
  AttemptId,
  type AttemptRecord,
  type AttemptSummary,
  BoardId,
  type BoardRecord,
  BoardSnapshot,
  CommandId,
  DEFAULT_PRESENCE_RESUME_PROTOCOL,
  type DeterministicJobRecord,
  DeterministicJobId,
  EvidenceId,
  FindingId,
  GoalIntakeId,
  GoalIntakeSource,
  type GoalIntakeRecord,
  type GoalIntakeResult,
  HandoffId,
  type KnowledgePageRecord,
  KnowledgePageId,
  MessageId,
  MergeOperationId,
  type ModelSelection,
  PresenceAttachThreadInput,
  PresenceCleanupWorkspaceInput,
  PresenceCreateFollowUpProposalInput,
  PresenceCreateAttemptInput,
  PresenceCreateDeterministicJobInput,
  PresenceCreatePromotionCandidateInput,
  PresenceCancelSupervisorRunInput,
  PresenceDismissFindingInput,
  PresenceEvaluateSupervisorActionInput,
  PresenceGetRepositoryCapabilitiesInput,
  PresenceMaterializeFollowUpInput,
  PresencePrepareWorkspaceInput,
  PresenceProjectionHealthStatus,
  PresenceRecordValidationWaiverInput,
  PresenceResolveFindingInput,
  PresenceRunAttemptValidationInput,
  type PresenceAcceptanceChecklistItem,
  PresenceCreateTicketInput,
  PresenceGetBoardSnapshotInput,
  PresenceImportRepositoryInput,
  PresenceListRepositoriesInput,
  PresenceMergeOperationStatus,
  PresenceScanRepositoryCapabilitiesInput,
  PresencePromotionStatus,
  PresenceReviewDecisionKind,
  PresenceReviewRecommendationKind,
  PresenceReviewPromotionCandidateInput,
  PresenceRpcError,
  PresenceSubmitGoalIntakeInput,
  PresenceStartSupervisorRunInput,
  PresenceSaveAttemptEvidenceInput,
  PresenceSaveSupervisorHandoffInput,
  PresenceSaveWorkerHandoffInput,
  PresenceStartAttemptSessionInput,
  PresenceAttemptStatus,
  PresenceAttemptOutcomeKind,
  PresenceFindingDisposition,
  PresenceFindingSeverity,
  PresenceFindingSource,
  PresenceFindingStatus,
  PresenceFollowUpProposalKind,
  PresenceJobStatus,
  PresenceKnowledgeFamily,
  PresenceReviewerKind,
  PresenceProjectionScopeType,
  PresenceSupervisorRunStage,
  PresenceSupervisorRunStatus,
  type RepositoryCapabilityScanRecord,
  type RepositoryCapabilityCommand,
  RepositoryCommandKind,
  PresenceTicketPriority,
  PresenceSubmitReviewDecisionInput,
  PresenceTicketStatus,
  PresenceUpdateTicketInput,
  PresenceUpsertKnowledgePageInput,
  PresenceWorkspaceStatus,
  ProviderKind,
  ProposedFollowUpId,
  type PromotionCandidateRecord,
  PromotionCandidateId,
  ProjectId,
  RepositoryId,
  type RepositorySummary,
  ReviewDecisionId,
  ReviewArtifactId,
  type ReviewChecklistAssessmentItem,
  type ReviewEvidenceItem,
  SupervisorRunId,
  type AttemptOutcomeRecord,
  type FindingRecord,
  type MergeOperationRecord,
  type ProposedFollowUpRecord,
  type ProjectionHealthRecord,
  type ReviewArtifactRecord,
  type ReviewDecisionRecord,
  type SupervisorPolicyDecision,
  type SupervisorActionKind,
  type SupervisorHandoffRecord,
  type SupervisorRunRecord,
  type TicketSummaryRecord,
  ThreadId,
  TicketId,
  TrimmedNonEmptyString,
  type TicketRecord,
  type ValidationWaiverRecord,
  ValidationWaiverId,
  ValidationRunId,
  type ValidationRunRecord,
  type WorkspaceRecord,
  WorkspaceId,
  type WorkerHandoffRecord,
  type AttemptEvidenceRecord,
} from "@t3tools/contracts";
import { resolveAutoFeatureBranchName } from "@t3tools/shared/git";
import { Effect, Result, Schema } from "effect";
import * as SqlClient from "effect/unstable/sql/SqlClient";

import { GitCore } from "../../../git/Services/GitCore.ts";
import { OrchestrationEngineService } from "../../../orchestration/Services/OrchestrationEngine.ts";
import type { PresenceControlPlaneShape } from "../../Services/PresenceControlPlane.ts";
import { ProviderRegistry } from "../../../provider/Services/ProviderRegistry.ts";
import { SupervisorPolicy } from "../../Services/SupervisorPolicy.ts";
import { runProcess } from "../../../processRunner.ts";
import { makePresenceAttemptService } from "./PresenceAttemptService.ts";
import { makePresenceBoardService } from "./PresenceBoardService.ts";
import { makePresenceProjectionRuntime } from "./PresenceProjectionRuntime.ts";
import { makePresenceReviewMergeService } from "./PresenceReviewMergeService.ts";
import { makePresenceRuntimeSupport } from "./PresenceRuntimeSupport.ts";
import {
  buildAttemptBootstrapPrompt,
  buildReviewWorkerPrompt,
  buildSupervisorPromptSections,
  buildReviewWorkerSystemPrompt,
  buildSupervisorSystemPrompt,
  buildWorkerContinuationPrompt,
  buildWorkerSystemPrompt,
  formatBulletList,
  formatChecklistMarkdown,
  reviewResultSupportsMechanismChecklist,
} from "./PresencePrompting.ts";
import {
  REVIEW_THREAD_TIMEOUT_MS,
  addMillisecondsIso,
  buildBlockerSummaries,
  buildRunnableValidationCommands,
  checklistIsComplete,
  chooseDefaultModelSelection,
  collapseWhitespace,
  conciseProjectionErrorMessage,
  collectAttemptActivityEntries,
  decodeJson,
  describeUnknownError,
  encodeJson,
  formatOptionalText,
  hasAttemptExecutionContext,
  isEvidenceChecklistItem,
  isThreadSettled,
  isMechanismChecklistItem,
  isModelSelectionAvailable,
  isPresenceRpcError,
  isSqliteUniqueConstraintError,
  isValidationChecklistItem,
  makeId,
  makeValidationShellInvocation,
  mergeOperationHasCleanupPending,
  mergeOperationIndicatesFailure,
  mergeOperationIsNonTerminal,
  normalizeGoalParts,
  normalizeIdList,
  nowIso,
  presenceError,
  projectionErrorPath,
  projectionIsRepairEligible,
  projectionRepairKey,
  projectionRetryDelayMs,
  readLatestAssistantReasoningFromThread,
  readLatestReviewResultFromThread,
  readTextFileIfPresent,
  repeatedFailureKindForTicket,
  reasoningIsStale,
  sanitizeProjectionSegment,
  shortTitle,
  titleFromPath,
  summarizeCommandOutput,
  truncateText,
  uniqueStrings,
  type AttemptActivityEntry,
  type BlockerSummary,
  type ParsedPresenceReviewFinding,
  type ParsedPresenceReviewResult,
  type ProjectionHealthStatus,
  type ProjectionScopeType,
  type WorkerReasoningSource,
} from "./PresenceShared.ts";
import { makePresenceStore } from "./PresenceStore.ts";
import { makePresenceSupervisorRuntime } from "./PresenceSupervisorRuntime.ts";

export const makePresenceControlPlane = Effect.gen(function* () {
  const sql = yield* SqlClient.SqlClient;
  const gitCore = yield* GitCore;
  const orchestrationEngine = yield* OrchestrationEngineService;
  const providerRegistry = yield* ProviderRegistry;
  const supervisorPolicy = yield* SupervisorPolicy;

  const persistSupervisorRun = (input: {
    runId: string;
    boardId: string;
    sourceGoalIntakeId: string | null;
    scopeTicketIds: ReadonlyArray<string>;
    status: PresenceSupervisorRunStatus;
    stage: PresenceSupervisorRunStage;
    currentTicketId: string | null;
    activeThreadIds: ReadonlyArray<string>;
    summary: string;
    createdAt?: string;
  }) =>
    Effect.gen(function* () {
      const now = nowIso();
      yield* sql`
        INSERT INTO presence_supervisor_runs (
          supervisor_run_id, board_id, source_goal_intake_id, scope_ticket_ids_json, status, stage,
          current_ticket_id, active_thread_ids_json, summary, created_at, updated_at
        ) VALUES (
          ${input.runId},
          ${input.boardId},
          ${input.sourceGoalIntakeId},
          ${encodeJson(input.scopeTicketIds)},
          ${input.status},
          ${input.stage},
          ${input.currentTicketId},
          ${encodeJson(input.activeThreadIds)},
          ${input.summary},
          ${input.createdAt ?? now},
          ${now}
        )
        ON CONFLICT(supervisor_run_id) DO UPDATE SET
          source_goal_intake_id = excluded.source_goal_intake_id,
          scope_ticket_ids_json = excluded.scope_ticket_ids_json,
          status = excluded.status,
          stage = excluded.stage,
          current_ticket_id = excluded.current_ticket_id,
          active_thread_ids_json = excluded.active_thread_ids_json,
          summary = excluded.summary,
          updated_at = excluded.updated_at
      `;
      const row = yield* readSupervisorRunById(input.runId);
      if (!row) {
        return yield* Effect.fail(presenceError(`Supervisor run '${input.runId}' could not be loaded.`));
      }
      yield* syncBoardProjectionBestEffort(input.boardId, "Supervisor run updated.");
      return row;
    });

  const getOrCreateCapabilityScan = (repositoryId: string) =>
    boardService.getOrCreateCapabilityScan(repositoryId);

  const store = makePresenceStore({ sql, nowIso });
  const {
    mapRepository,
    mapBoard,
    mapTicket,
    mapAttempt,
    mapWorkspace,
    mapSupervisorHandoff,
    mapWorkerHandoff,
    mapSupervisorRun,
    mapProjectionHealth,
    mapEvidence,
    mapValidationRun,
    mapFinding,
    mapReviewArtifact,
    mapProposedFollowUp,
    mapAttemptOutcome,
    mapKnowledgePage,
    mapPromotionCandidate,
    mapJob,
    mapReviewDecision,
    mapMergeOperation,
    mapCapabilityScan,
    mapValidationWaiver,
    mapGoalIntake,
    readRepositoryByWorkspaceRoot,
    readRepositoryById,
    readLatestCapabilityScan,
    readTicketForPolicy,
    readValidationWaiversForTicket,
    readAttemptWorkspaceContext,
    readLatestSupervisorHandoffForBoard,
    readLatestWorkerHandoffForAttempt,
    readSupervisorRunById,
    readLatestSupervisorRunForBoard,
    readMergeOperationById,
    readLatestMergeOperationForAttempt,
    persistMergeOperation,
    readLatestMergeApprovedDecisionForAttempt,
    readValidationRunsForAttempt,
    readValidationRunsForBatch,
    readRunningValidationBatchIdForAttempt,
    readFindingsForTicket,
    readReviewArtifactsForTicket,
    readFollowUpProposalsForTicket,
    readAttemptOutcomesForTicket,
    readOpenBlockingFindingsForTicket,
    createOrUpdateFinding,
    updateFindingStatus,
    resolveOpenFindings,
    createReviewArtifact,
    materializeReviewFindings,
    markTicketEvidenceChecklist,
    markTicketValidationChecklist,
    markTicketMechanismChecklist,
    writeAttemptOutcome,
  } = store;
  const runtimeSupport = makePresenceRuntimeSupport({
    sql,
    gitCore,
    orchestrationEngine,
    providerRegistry,
    makeId,
    nowIso,
    readAttemptWorkspaceContext,
    chooseDefaultModelSelection,
    isModelSelectionAvailable,
    uniqueStrings,
    decodeJson,
    presenceError,
  });
  const {
    ensureWorkspacePrepared,
    readThreadFromModel,
    readChangedFilesForWorkspace,
    resolveModelSelectionForAttempt,
    syncThreadWorkspaceMetadata,
    queueTurnStart,
    waitForClaimedThreadAvailability,
  } =
    runtimeSupport;
  let getBoardSnapshotInternalRef: (boardId: string) => Effect.Effect<BoardSnapshot, unknown, never> =
    () => Effect.die("Board snapshot service was not initialized.");
  let buildWorkerHandoffCandidateRef: (
    input: Parameters<
      ReturnType<typeof makePresenceAttemptService>["buildWorkerHandoffCandidate"]
    >[0],
  ) => ReturnType<ReturnType<typeof makePresenceAttemptService>["buildWorkerHandoffCandidate"]> =
    () => Effect.die("Worker handoff builder was not initialized.");
  const projectionRuntime = makePresenceProjectionRuntime({
    sql,
    nowIso,
    mapProjectionHealth,
    getBoardSnapshotInternal: (boardId: string) => getBoardSnapshotInternalRef(boardId),
    readTicketForPolicy,
    readThreadFromModel,
    buildBlockerSummaries,
  });
  const {
    buildAttemptActivityMarkdown,
    buildAttemptBlockersMarkdown,
    buildAttemptDecisionsMarkdown,
    buildAttemptFindingsMarkdown,
    buildAttemptProgressMarkdown,
    buildAttemptReviewMarkdown,
    buildAttemptValidationMarkdown,
    buildBrainIndexMarkdown,
    buildBrainLogMarkdown,
    buildKnowledgePageMarkdown,
    readProjectionHealth,
    runProjectionWorker,
    buildSupervisorHandoffMarkdown,
    buildSupervisorRunMarkdown,
    buildTicketCurrentSummaryMarkdown,
    buildTicketMarkdown,
    syncBoardProjectionBestEffort,
    syncProjectionStrict,
    syncTicketProjectionBestEffort,
    writeProjectionFile,
  } = projectionRuntime;

  const boardService = {
    ...makePresenceBoardService({
      sql,
      gitCore,
      supervisorPolicy,
      orchestrationEngine,
      providerRegistry,
      chooseDefaultModelSelection,
      readRepositoryByWorkspaceRoot,
      mapRepository,
      titleFromPath,
      makeId,
      nowIso,
      encodeJson,
      readTextFileIfPresent,
      uniqueStrings,
      syncBoardProjectionBestEffort,
      projectionIsRepairEligible,
      runProjectionWorker,
      readLatestCapabilityScan,
      readRepositoryById,
      mapBoard,
      mapTicket,
      mapAttempt,
      mapWorkspace,
      mapSupervisorHandoff,
      mapWorkerHandoff,
      mapSupervisorRun,
      mapProjectionHealth,
      mapEvidence,
      mapValidationRun,
      mapFinding,
      mapReviewArtifact,
      mapProposedFollowUp,
      mapAttemptOutcome,
      mapKnowledgePage,
      mapPromotionCandidate,
      mapJob,
      mapReviewDecision,
      mapMergeOperation,
      mapCapabilityScan,
      mapValidationWaiver,
      mapGoalIntake,
      syncTicketProjectionBestEffort,
      syncProjectionStrict,
      decodeJson,
      readTicketForPolicy,
      readAttemptWorkspaceContext,
      readValidationWaiversForTicket,
      readFindingsForTicket,
      readAttemptOutcomesForTicket,
      readValidationRunsForAttempt,
      normalizeGoalParts,
      shortTitle,
      readThreadFromModel,
      buildWorkerHandoffCandidate: (input) => buildWorkerHandoffCandidateRef(input),
      presenceError,
    }),
  };
  const {
    saveSupervisorHandoff,
    createFollowUpProposal,
    materializeFollowUp,
    syncTicketProjection,
    syncBrainProjection,
    upsertKnowledgePage,
    createPromotionCandidate,
    reviewPromotionCandidate,
    createDeterministicJob,
    evaluateSupervisorAction,
    recordValidationWaiver,
    submitGoalIntake,
    getBoardSnapshotInternal,
    ensurePromotionCandidateForAcceptedAttempt,
    evaluateSupervisorActionInternal,
  } = boardService;
  getBoardSnapshotInternalRef = getBoardSnapshotInternal;
  const attemptService = makePresenceAttemptService({
    sql,
    removeWorktree: (input) => gitCore.removeWorktree(input),
    readAvailableProviders: () => providerRegistry.getProviders,
    dispatchOrchestration: (command) => orchestrationEngine.dispatch(command),
    makeId,
    nowIso,
    presenceError,
    isPresenceRpcError,
    isSqliteUniqueConstraintError,
    readAttemptOutcomesForTicket,
    repeatedFailureKindForTicket,
    createOrUpdateFinding,
    syncTicketProjectionBestEffort,
    ensureWorkspacePrepared,
    readAttemptWorkspaceContext,
    syncThreadWorkspaceMetadata,
    writeAttemptOutcome,
    evaluateSupervisorActionInternal,
    decodeJson,
    isModelSelectionAvailable,
    chooseDefaultModelSelection,
    buildWorkerSystemPrompt,
    readLatestWorkerHandoffForAttempt,
    readLatestSupervisorHandoffForBoard,
    buildAttemptBootstrapPrompt,
    waitForClaimedThreadAvailability,
    mapAttempt,
    encodeJson,
    markTicketEvidenceChecklist,
    getOrCreateCapabilityScan,
    buildRunnableValidationCommands,
    readRunningValidationBatchIdForAttempt,
    readValidationRunsForBatch,
    runProcess,
    makeValidationShellInvocation,
    summarizeCommandOutput,
    describeUnknownError,
    markTicketValidationChecklist,
    readFindingsForTicket,
    updateFindingStatus,
    hasAttemptExecutionContext,
    readThreadFromModel,
    readChangedFilesForWorkspace,
    readValidationRunsForAttempt,
    readLatestAssistantReasoningFromThread,
    buildBlockerSummaries,
    uniqueStrings,
    isThreadSettled,
  });
  const {
    buildWorkerHandoffCandidate,
    createAttempt,
    startAttemptSession,
    saveWorkerHandoff,
    runAttemptValidation,
    synthesizeWorkerHandoffFromThread,
  } = attemptService;
  buildWorkerHandoffCandidateRef = buildWorkerHandoffCandidate;
  const reviewMergeService = makePresenceReviewMergeService({
    presenceError,
    gitExecute: (input) => gitCore.execute(input),
    gitStatusDetails: (cwd) => gitCore.statusDetails(cwd),
    gitPrepareCommitContext: (cwd) => gitCore.prepareCommitContext(cwd),
    gitCommit: (cwd, title, body) => gitCore.commit(cwd, title, body ?? ""),
    removeWorktree: (input) => gitCore.removeWorktree(input),
    dispatchOrchestration: (command) => orchestrationEngine.dispatch(command),
    resolveModelSelectionForAttempt,
    makeId,
    nowIso,
    buildReviewWorkerSystemPrompt,
    buildReviewWorkerPrompt,
    queueTurnStart,
    readTicketForPolicy,
    readLatestWorkerHandoffForAttempt,
    createOrUpdateFinding,
    sql,
    createReviewArtifact,
    syncTicketProjectionBestEffort,
    readLatestCapabilityScan,
    readLatestMergeApprovedDecisionForAttempt,
    readAttemptWorkspaceContext,
    readLatestMergeOperationForAttempt,
    evaluateSupervisorActionInternal,
    persistMergeOperation,
    readMergeOperationById,
    updateFindingStatus,
    writeAttemptOutcome,
    resolveOpenFindings,
    materializeReviewFindings,
    markTicketMechanismChecklist,
    syncThreadWorkspaceMetadata,
  });
  const { startReviewSession, blockTicketForReviewFailure, applyReviewDecisionInternal } =
    reviewMergeService;
  const supervisorRuntime = makePresenceSupervisorRuntime({
    getBoardSnapshotInternal,
    readLatestSupervisorRunForBoard,
    readSupervisorRunById,
    persistSupervisorRun,
    saveSupervisorHandoff,
    normalizeIdList,
    nowIso,
    makeId,
    isSqliteUniqueConstraintError,
    presenceError,
    projectionIsRepairEligible,
    runProjectionWorker,
    createAttempt,
    readAttemptWorkspaceContext,
    startAttemptSession,
    readThreadFromModel,
    isThreadSettled,
    synthesizeWorkerHandoffFromThread,
    syncTicketProjectionBestEffort,
    readLatestWorkerHandoffForAttempt,
    readValidationRunsForAttempt,
    runAttemptValidation,
    uniqueStrings,
    saveWorkerHandoff,
    createOrUpdateFinding,
    sql,
    resolveModelSelectionForAttempt,
    queueTurnStart,
    buildWorkerContinuationPrompt,
    startReviewSession,
    addMillisecondsIso,
    reviewThreadTimeoutMs: REVIEW_THREAD_TIMEOUT_MS,
    readLatestReviewResultFromThread,
    blockTicketForReviewFailure,
    applyReviewDecisionInternal,
    reviewResultSupportsMechanismChecklist,
    ensurePromotionCandidateForAcceptedAttempt,
  });

  return {
    ...boardService,
    ...attemptService,
    ...reviewMergeService,
    ...supervisorRuntime,
  } satisfies PresenceControlPlaneShape;
});
